apps/loginApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^success$', views.success, name='success'),
    url(r'^logout$', views.logout, name='logout'),
]

book_reviews/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('apps.loginApp.urls', namespace='users')),
    url(r'^books/', include('apps.reviewApp.urls', namespace='reviews')),
]

apps/loginApp/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Count
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
PASSWORD_REGEX = re.compile(r'\d.*[A-Z]|[A-Z].*\d')

class UserManager(models.Manager):
    def isValidRegistration(self, request):
        errors = []
        if len(request.POST['first_name']) < 2:
            errors.append('First Name can not be less than 2 characters')
        elif not request.POST['first_name'].isalpha():
            errors.append('First Name should only contain letters')

        if len(request.POST['last_name']) < 2:
            errors.append('Last Name can not be less than 2 characters')
        elif not request.POST['last_name'].isalpha():
            errors.append('Last Name should only contain letters')

        if len(request.POST['email']) < 1:
            errors.append('Email can not be empty')
        elif not EMAIL_REGEX.match(request.POST['email']):
            errors.append('Email is not valid')

        if len(request.POST['password']) < 1:
            errors.append('Password can not be empty')
        elif len(request.POST['password']) < 8:
            errors.append('Password should be more than 7 characters')
        elif not PASSWORD_REGEX.match(request.POST['password']):
            errors.append('Password should contain at least one upper case letter and one number')

        if request.POST['password'] != request.POST['confirm_password']:
            errors.append('Password and Confirm Password does not match!')

        try:
            user = User.objects.get(email = request.POST['email'])
            errors.append('This email is already being used')
        except ObjectDoesNotExist:
            pass

        if len(errors) > 0:
            return [False, errors]

        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        user = self.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=pw_hash)
        return [True, user]

    def isValidLogin(self, request):
        errors = []
        try:
            user = User.objects.get(email = request.POST['email'])
            password = user.password.encode()
            login_input_password = request.POST['password'].encode()
            print "*"*40
            print password
            print bcrypt.hashpw(login_input_password, password)
            print "*"*40
            if bcrypt.hashpw(login_input_password, password) == password:
                return (True, user)
            else:
                errors.append("Sorry, no password match")
                return (False, errors)
        except ObjectDoesNotExist:
            pass
        errors.append("Sorry, no email found. Please try again.")
        return (False, errors)



    def fetch_user_info(self, id):
        return self.filter(id=id).annotate(total_reviews=Count('review'))[0]




class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    password = models.CharField(max_length=225)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/loginApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from models import User

def index(request):
    return render(request, 'loginApp/login.html')

def register(request):
    data = User.objects.isValidRegistration(request)
    if data[0] == False:
        print_messages(request, data[1])
        return redirect(reverse('users:index'))
    return log_user_in(request, data[1])

def login(request):
    data = User.objects.isValidLogin(request)
    if data[0] == False:
        print_messages(request, data[1])
        return redirect(reverse('users:index'))
    return log_user_in(request, data[1])

def log_user_in(request, user):
    request.session['user'] = {
        'id' : user.id,
        'first_name' : user.first_name,
        'last_name' : user.last_name,
        'email' : user.email,
    }
    return redirect(reverse('users:success'))

def success(request):
    if not 'user' in request.session:
        return redirect(reverse('users:index'))
    return redirect(reverse('reviews:index'))

def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.ERROR, message)

def logout(request):
    request.session.pop('user')
    return redirect(reverse('users:index'))

apps/loginApp/templates/loginApp/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Login & Reg | Home</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <h4{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h4>
        {% endfor %}
      </div>
      {% endif %}
      <form action="{% url 'users:register' %}" method="post">
        <h3>Registration</h3>
        {% csrf_token %}
        <div class="form-group">
          <label>First Name:</label>
          <input type="text" class="form-control" name="first_name" placeholder="First Name">
        </div>
        <div class="form-group">
          <label>Last Name:</label>
          <input type="text" class="form-control" name="last_name" placeholder="Last Name">
        </div>
        <div class="form-group">
          <label>Email:</label>
          <input type="email" class="form-control" name="email" placeholder="Email">
        </div>
        <div class="form-group">
          <label>Password:</label>
          <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <div class="form-group">
          <label>Confirm Password:</label>
          <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
        </div>
        <input type="submit" class="btn btn-primary pull-right" value="Register">
      </form>
      <form action="{% url 'users:login' %}" method="post">
        <h3>Login</h3>
        {% csrf_token %}
        <div class="form-group">
          <label>Email:</label>
          <input type="text" class="form-control" name="email" placeholder="Email">
        </div>
        <div class="form-group">
          <label>Password:</label>
          <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <input type="submit" class="btn btn-primary pull-right" value="Login">
      </form>
    </div>
  </body>
</html>