apps/loginApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^success$', views.success, name='success'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/reviewApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^(?P<id>\d+)$', views.show, name='show'),
    url(r'^users/(?P<id>\d+)$', views.show_user, name='show_user'),
]

book_reviews/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('apps.loginApp.urls', namespace='users')),
    url(r'^books/', include('apps.reviewApp.urls', namespace='reviews')),
]

apps/reviewApp/models.py
from __future__ import unicode_literals
from ..loginApp.models import User
from django.db import models

class ReviewManager(models.Manager):
    def create_review(self, form_data, user_id):
        try:
            # author = self.fetch_author(form_data)
            book = self.fetch_book(form_data)
            # book = Book.objects.create(title=form_data['title'], author=author)
            user = User.objects.get(id=user_id)
            new_review = Review.objects.create(review=form_data['review'], rating=form_data['rating'], user=user, book=book)
            return (True, new_review)
        except:
            return (False, ["There was a problem creating the review..."])

    def fetch_book(self, form_data):
        try:
            book = Book.objects.get(id=form_data['book_id'])
        except:
            author = self.fetch_author(form_data)
            book = Book.objects.create(title=form_data['title'], author=author)
        return book

    def fetch_author(self, form_data):
        try:
            print 'author_id::::::::::', form_data['author_id']
            author = Author.objects.get(id=form_data['author_id'])
        except:
            print 'errorrrr'
            author = Author.objects.create(name=form_data['new_author'])
        return author

    def fetch_recent(self):
        return Review.objects.all().order_by('-created_at')[:3]



class Author(models.Model):
    name = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=45)
    author = models.ForeignKey('Author')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Review(models.Model):
    review = models.TextField(max_length=1000)
    rating = models.IntegerField()
    user = models.ForeignKey('loginApp.User')
    book = models.ForeignKey('Book', default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ReviewManager()

apps/reviewApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from models import Author, Book, Review
from ..loginApp.models import User
from ..loginApp.views import print_messages


def check_logged_in(request):
    return 'user' in request.session

# GET Home
def index(request):
    if not check_logged_in(request):
        return redirect(reverse('users:index'))

    context = {
        'reviews' : Review.objects.fetch_recent(),
        'books' : Book.objects.all()
    }
    return render(request, 'reviewApp/index.html', context)

# GET create new review
def new(request):
    if not check_logged_in(request):
        return redirect(reverse('users:index'))

    context = {
        'books' : Book.objects.all(),
        'authors' : Author.objects.all()
    }
    return render(request, 'reviewApp/new.html', context)

# POST book review
def create(request):
    if not check_logged_in(request):
        return redirect(reverse('users:index'))

    print "UserId::::::: ", request.session['user']['id']
    result = Review.objects.create_review(request.POST, request.session['user']['id'])

    if result[0] == True:
        return redirect(reverse('reviews:index', kwargs={'id': result[1].book.id }))
    else:
        print_messages(request, result[1])
        return redirect(reverse('reviews:new'))

# GET show book
def show(request, id):
    if not check_logged_in(request):
        return redirect(reverse('users:index'))

    book = Book.objects.get(id=id)
    return render(request, 'reviewApp/show.html', { 'book' : book })


def show_user(request, id):
    if not check_logged_in(request):
        return redirect(reverse('users:index'))

    user = User.objects.fetch_user_info(id)
    return render(request, 'reviewApp/show_user.html', { 'user' : user })

apps/reviewApp/templates/reviewApp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Books Home</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <h4>Welcome {{ request.session.user.first_name }}!</h4>
        <a class="btn btn-info" href="{% url 'reviews:new' %}" role="button">Add book and Review</a>
        <a class="btn btn-warning" href="{% url 'users:logout' %}" role="button">Logout</a>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <h3>Recent book reviews:</h3>
          {% for review in reviews %}
          <h4>{{review.book.title}}</h4>
          <h5>Rating: {{review.rating}}</h5>
          <p><a href="{% url 'reviews:show_user' id=review.user.id%}">{{review.user.first_name}}</a> says: {{review.review}}</p>
          <p>Posted on {{review.created_at}}</p>
          <hr>
          {% endfor %}
        </div>
        <div class="col-xs-6">
          <h3>Other books with reviews:</h3>
          {% for book in books %}
            <p><a href="{% url 'reviews:show' id=book.id %}">{{book.title}}</a></p>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

apps/reviewApp/templates/reviewApp/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <a class="btn btn-warning" href="{% url 'reviews:index' %}" role="button">Home</a>
        <a class="btn btn-warning" href="{% url 'users:logout' %}" role="button">Logout</a>
      </div>
      <h3>Add a New Book Title and a Review</h3>
      <form action="{% url 'reviews:create' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label>Book Title:</label>
          <input type="text" class="form-control" name="title" placeholder="Book Title">
        </div>
        <div class="form-group">
          <label>Author:</label>
          <select class="form-control" name="author_id">
            <option value="None">Author Name</option>
            {% for author in authors %}
            <option value="{{author.id}}">{{author.name}}</option>
            {% endfor %}
          </select>
          <label>...or add a new author:</label>
          <input type="text" class="form-control" name="new_author" placeholder="Author">
        </div>
        <div class="form-group">
          <label>Review:</label>
          <input type="text" class="form-control" name="review" placeholder="Review">
        </div>
        <label>Rating:</label>
        <select class="form-control" name="rating">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        <input class="btn btn-success" type="submit" value="Add Book and Review">
      </form>
    </div>
  </body>
</html>

apps/reviewApp/templates/reviewApp/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <a class="btn btn-warning" href="{% url 'reviews:index' %}" role="button">Home</a>
        <a class="btn btn-warning" href="{% url 'users:logout' %}" role="button">Logout</a>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <h3>{{book.title}}</h3>
          <h4>Author: {{book.author.name}}</h4>
          <h3><b>Reviews:</b></h3>
          <hr>
          {% for review in book.review_set.all %}
          <h4>Rating: {{review.rating}}</h4>
          <p><a href="{% url 'reviews:show_user' id=review.user.id%}">{{review.user.first_name}}</a> says: {{review.review}}</p>
          <p>Posted on {{review.created_at}}</p>
          <hr>
          {% endfor %}
        </div>
        <div class="col-xs-6">
          <h3><b>Add a Review:</b></h3>
          <form action="{% url 'reviews:create' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{book.id}}">
            <div class="form-group">
              <label>Review:</label>
              <input type="text" class="form-control" name="review" placeholder="Review">
            </div>
            <label>Rating:</label>
            <select class="form-control" name="rating">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select>
            <input type="submit" value="Submit new review">
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

apps/reviewApp/templates/reviewApp/show_user.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>User Reviews</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <a class="btn btn-warning" href="{% url 'reviews:index' %}" role="button">Home</a>
        <a class="btn btn-info" href="{% url 'reviews:new' %}" role="button">Add book and Review</a>
        <a class="btn btn-warning" href="{% url 'users:logout' %}" role="button">Logout</a>
      </div>
      <div class="row">
        <h3>User Alias: {{user.first_name}}</h3>
        <h4>Name: {{user.first_name}} {{user.last_name}}</h4>
        <h4>Email: {{user.email}}</h4>
        <h4>Total Review: {{user.total_reviews}}</h4>
        <br>
        <h3>Posted Reviews on the following books:</h3>
        {% for review in user.review_set.all %}
          <p><a href="{% url 'reviews:show' id=review.book.id %}">{{review.book.title}}</a></p>
        {% endfor %}
      </div>
    </div>
  </body>
</html>